# -*- coding: utf-8 -*-
"""StudentManagementSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afcHUMFrEgdhqbfJP4UxLbJq8UkZ16NP
"""

# Student Management System using Python
# Python Summer Internship – March 2025
# UpSkill Campus

students = {}

def add_student():
    roll = input("Enter Roll Number: ")
    name = input("Enter Student Name: ")
    marks = input("Enter Marks: ")
    students[roll] = {
        "Name": name,
        "Marks": marks
    }
    print("Student added successfully.\n")

def view_students():
    if not students:
        print("No student records found.\n")
    else:
        print("\nStudent Records:")
        for roll, details in students.items():
            print(f"Roll No: {roll}, Name: {details['Name']}, Marks: {details['Marks']}")
        print()

def delete_student():
    roll = input("Enter Roll Number to delete: ")
    if roll in students:
        del students[roll]
        print("Student record deleted successfully.\n")
    else:
        print("Student not found.\n")

while True:
    print("===== Student Management System =====")
    print("1. Add Student")
    print("2. View Students")
    print("3. Delete Student")
    print("4. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_student()
    elif choice == "2":
        view_students()
    elif choice == "3":
        delete_student()
    elif choice == "4":
        print("Exiting program.")
        break
    else:
        print("Invalid choice. Try again.\n")